config/routes.rb
Rails.application.routes.draw do
	root 'pokemons#index'
	resources :bonds, only: [:destroy, :create]
	resource :session
	resources :pokemons, :users, :moves
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bond.rb
class Bond < ApplicationRecord
	belongs_to :user
	belongs_to :pokemon
end

app/models/move.rb
class Move < ApplicationRecord
	has_and_belongs_to_many :pokemons
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	has_and_belongs_to_many :moves
	has_many :bonds, dependent: :destroy
	has_many :users, through: :bonds
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bonds, dependent: :destroy
	has_many :pokemons, through: :bonds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
  	if User.exists?(session[:user_id])
  		@current_user = User.find(session[:user_id])
  	else
  		@current_user = nil
  	end
  end
end

app/controllers/bonds_controller.rb
class BondsController < ApplicationController
	def destroy
		@user = @current_user
		@pokemon = Pokemon.find(params[:id])
		@user.bonds.find_by(pokemon_id: @pokemon).destroy
		redirect_to @user, alert: "Pokemon was released into the wild"
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
	before_action :set_move, only: [:show, :destroy, :update, :edit]
	def index
		@moves = Move.all
	end
	def new
		@move = Move.new
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def create
		@move = Move.create(move_params)
		error "create"
	end
	def edit
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def update
		@move.update(move_params)
		error "update"
	end
	def destroy
		@move.destroy
		redirect_to "/moves", alert: "Move was successfully deleted."
	end
	def show

	end

	private

	def set_move
		@move = Move.find(params[:id])
	end
	
	def move_params
		params.require(:move).permit(:name, :damage, :dps, :poke_type, :quick_move)
	end

	def error action
		if @move.save
			redirect_to @move, notice: "Move was successfully #{action}d."
		else
			message = "| "
			@move.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_move_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_move_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @move, alert: "#{ message }"
			end
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		input_email = params[:user][:email]
		if User.exists?(email: input_email)
			@user = User.find_by(email: input_email)
			puts "User found!"
			if @user.password == params[:user][:password]
				session[:user_id] = @user.id
				redirect_to user_path(@user.id), notice: "User successfully signed in."
			else
				puts "Incorrect password"
				redirect_to new_session_path, notice: "Wrong password, please try again"
			end
		else
			puts "User does not exist"
			redirect_to new_session_path, notice: "User does not exist"
		end
	end
	def destroy
		reset_session
		redirect_to :root, notice: "User successfully signed out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :destroy, :update, :edit]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.create(user_params)
		session[:user_id] = @user.id
		error "create"
	end
	def edit
	end
	def update
		@user.update(user_params)
		error "update"
	end
	def destroy
		@user.destroy
		redirect_to "/users", alert: "User was successfully deleted."
	end
	def show
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :password, :first_name, :last_name)
	end

	def error action
		if @user.save
			redirect_to @user, notice: "User was successfully #{action}d."
		else
			message = "| "
			@user.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_user_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_user_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @user, alert: "#{ message }"
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonds_helper.rb
module BondsHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="form">
	<%= form_for @user do |f| %>
		<div class="form-item">
			<h4>First Name</h4>
			<%= f.text_field :first_name %>
		</div>

		<div class="form-item">
			<h4>Last Name</h4>
			<%= f.text_field :last_name %>
		</div>

		<div class="form-item">
			<h4>Email</h4>
			<%= f.text_field :email %>
		</div>

		<div class="form-item">
			<h4>Password</h4>
			<%= f.password_field :password %>
		</div>
		
		<div class="form-item">
			<%= f.submit "Update", class: "remove" %>
		</div>
	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">
	<% @users.each do |user| %>
		<div class="form">
			<h1><%= link_to "#{ user.first_name } #{ user.last_name }", user_path(user) %></h1>
			<h3><%= user.email %></h3>
			<div class="container">
				<% user.pokemons.each do |pokemon| %>
					<img class="img" src="https://img.pokemondb.net/sprites/black-white/anim/normal/<%= pokemon.name.downcase %>.gif" width="50px" height="50px">
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/users/new.html.erb
<div class="form">
	<%= form_for @user do |f| %>
		<div class="form-item">
			<h4>First Name</h4>
			<%= f.text_field :first_name %>
		</div>

		<div class="form-item">
		<h4>Last Name</h4>
			<%= f.text_field :last_name %>
		</div>

		<div class="form-item">
			<h4>Email</h4>
			<%= f.text_field :email %>
		</div>

		<div class="form-item">
			<h4>Password</h4>
			<%= f.password_field :password %>
		</div>
		
		<div class="form-item">
			<%= f.submit "Sign Up", class: "remove" %>
		</div>
	<% end %>
</div>

app/views/users/show.html.erb
<div class="form">
	<% if @current_user %>
		<p class="remove">
			<%= link_to "Edit", edit_user_path(@user) %> | 
			<%= link_to 'Delete', @pokemon,
		    	method: :delete,
		    	data: { confirm: 'Are you sure you want to delete?' } %>
		</p>
	<% end %>
	<h1><%= @user.email %></h1>
	<h3>Name: <%= @user.first_name %> <%= @user.last_name %></h3>
	<div class="container">
		<% @user.pokemons.each do |pokemon| %>
			<div class="owned-pokemon">
				<h3><%= link_to pokemon.name, pokemon_path(pokemon) %></h3>
				<img class="img" src="https://img.pokemondb.net/sprites/black-white/anim/normal/<%= pokemon.name.downcase %>.gif" width="100px" height="100px">
				<% if @current_user %>
					<%= link_to 'Release Pokemon', bond_path(pokemon),
				    	method: :delete,
				    	data: { confirm: 'Are you sure you want to release pokemon?' } %>
			    <% end %>
			</div>
		<% end %>
	</div>
</div>