config/routes.rb
Rails.application.routes.draw do
	root 'pokemons#index'
	resources :bonds, only: [:destroy, :create]
	resource :session
	resources :pokemons, :users, :moves
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bond.rb
class Bond < ApplicationRecord
	belongs_to :user
	belongs_to :pokemon
end

app/models/move.rb
class Move < ApplicationRecord
	has_and_belongs_to_many :pokemons
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	has_and_belongs_to_many :moves
	has_many :bonds, dependent: :destroy
	has_many :users, through: :bonds
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bonds, dependent: :destroy
	has_many :pokemons, through: :bonds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
  	if User.exists?(session[:user_id])
  		@current_user = User.find(session[:user_id])
  	else
  		@current_user = nil
  	end
  end
end

app/controllers/bonds_controller.rb
class BondsController < ApplicationController
	def destroy
		@user = @current_user
		@pokemon = Pokemon.find(params[:id])
		@user.bonds.find_by(pokemon_id: @pokemon).destroy
		redirect_to @user, alert: "Pokemon was released into the wild"
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
	before_action :set_move, only: [:show, :destroy, :update, :edit]
	def index
		@moves = Move.all
	end
	def new
		@move = Move.new
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def create
		@move = Move.create(move_params)
		error "create"
	end
	def edit
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def update
		@move.update(move_params)
		error "update"
	end
	def destroy
		@move.destroy
		redirect_to "/moves", alert: "Move was successfully deleted."
	end
	def show

	end

	private

	def set_move
		@move = Move.find(params[:id])
	end
	
	def move_params
		params.require(:move).permit(:name, :damage, :dps, :poke_type, :quick_move)
	end

	def error action
		if @move.save
			redirect_to @move, notice: "Move was successfully #{action}d."
		else
			message = "| "
			@move.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_move_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_move_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @move, alert: "#{ message }"
			end
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		input_email = params[:user][:email]
		if User.exists?(email: input_email)
			@user = User.find_by(email: input_email)
			puts "User found!"
			if @user.password == params[:user][:password]
				session[:user_id] = @user.id
				redirect_to user_path(@user.id), notice: "User successfully signed in."
			else
				puts "Incorrect password"
				redirect_to new_session_path, notice: "Wrong password, please try again"
			end
		else
			puts "User does not exist"
			redirect_to new_session_path, notice: "User does not exist"
		end
	end
	def destroy
		reset_session
		redirect_to :root, notice: "User successfully signed out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :destroy, :update, :edit]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.create(user_params)
		session[:user_id] = @user.id
		error "create"
	end
	def edit
	end
	def update
		@user.update(user_params)
		error "update"
	end
	def destroy
		@user.destroy
		redirect_to "/users", alert: "User was successfully deleted."
	end
	def show
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :password, :first_name, :last_name)
	end

	def error action
		if @user.save
			redirect_to @user, notice: "User was successfully #{action}d."
		else
			message = "| "
			@user.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_user_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_user_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @user, alert: "#{ message }"
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonds_helper.rb
module BondsHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/moves/edit.html.erb
<div class="form">
	<%= form_for @move do |f| %>
		 <div class="switch switch-blue">
		    <input type="radio" class="switch-input" name="move[quick_move]" value="true" id="quick" <%= @move.quick_move == true ? "checked" : ""  %> >
		    <label for="quick" class="switch-label switch-label-off">Quick Move</label>
		    <input type="radio" class="switch-input" name="move[quick_move]" value="false" id="main" <%= @move.quick_move == false ? "checked" : ""  %> >
		    <label for="main" class="switch-label switch-label-on">Main Move</label>
		    <span class="switch-selection"></span>
		</div>

		<div class="form-item">
			<h4>Name</h4>
			<%= f.text_field :name %>
		</div>

		<div class="form-item">
			<h4>Damage</h4>
			<%= f.text_field :damage %>
		</div>

		<div class="form-item">
			<h4>DPS</h4>
			<%= f.text_field :dps %>
		</div>

		<div class="form-item">
			<h4>Move Type</h4>
			<div class="type-wrapper">
				<% @types.each do |type| %>
					<label>
						<input type="radio" name="move[poke_type]" value="<%= type %>" <%= @move.poke_type == type ? "checked" : ""  %> ></input>
						<span class="type-icon type-<%= type.downcase %>"><%= type %></span>
					</label>
				<% end %>
			</div>
	   	</div>
		
		<div class="form-item">
			<%= f.submit "Update Move", class: "remove" %>
		</div>
	<% end %>
</div>

app/views/moves/index.html.erb
<div class="container">
	<div class="column">
		<div class="menu">
			<% if @current_user %>
				<%= link_to image_tag("add.png", class: "add remove"), new_move_path %>
		    <% end %>
		</div>
		<h1>Quick Moves</h1>
		<% @moves.each do |move| %>
			<% if move.quick_move == true %>
				<h3><%= link_to move.name, move_path(move) %></h3>
			<% end %>
		<% end %>
	</div>
	<div class="column">
		<div class="menu">
			<% if @current_user %>
				<%= link_to image_tag("add.png", class: "add remove"), new_move_path %>
		    <% end %>
		</div>
		<h1>Main Moves</h1>
		<% @moves.each do |move| %>
			<% if move.quick_move == false %>
				<h3><%= link_to move.name, move_path(move) %></h3>
			<% end %>
		<% end %>
	</div>
</div>

app/views/moves/new.html.erb
<div class="form">
	<%= form_for @move do |f| %>
		 <div class="switch switch-blue">
		    <input type="radio" class="switch-input" name="move[quick_move]" value="true" id="quick" checked>
		    <label for="quick" class="switch-label switch-label-off">Quick Move</label>
		    <input type="radio" class="switch-input" name="move[quick_move]" value="false" id="main">
		    <label for="main" class="switch-label switch-label-on">Main Move</label>
		    <span class="switch-selection"></span>
		</div>

		<div class="form-item">
			<h4>Name</h4>
			<%= f.text_field :name %>
		</div>

		<div class="form-item">
			<h4>Damage</h4>
			<%= f.text_field :damage %>
		</div>

		<div class="form-item">
			<h4>DPS</h4>
			<%= f.text_field :dps %>
		</div>

		<div class="form-item">
			<h4>Move Type</h4>
			<div class="type-wrapper">
				<% @types.each do |type| %>
					<label>
						<input type="radio" class="check" name="move[poke_type]" value="<%= type %>" <%= type == "Normal" ? "checked" : ""  %>></input>
						<span for="check" class="type-icon type-<%= type.downcase %>"><%= type %></span>
					</label>
				<% end %>
			</div>
	   	</div>
		
		<div class="form-item">
			<%= f.submit "Create New Move", class: "remove" %>
		</div>
	<% end %>
</div>

app/views/moves/show.html.erb
<div class="container">
	<div class="column">
		<h1><%= @move.name %></h1>
		<div class="remove type-icon type-<%= @move.poke_type.downcase %>"><%= @move.poke_type %></div>
		<% if @current_user %>
			<p>
			<%= link_to "Edit", edit_move_path(@move) %> | 
			<%= link_to 'Delete', @move,
		    	method: :delete,
		    	data: { confirm: 'Are you sure you want to delete?' } %>
			</p>
		<% end %>
	</div>
	<div class="column">
		<h2>Damage: <%= @move.damage %></h2>
		<h2>DPS: <%= @move.dps %></h2>
	</div>
</div>
<div class="container">
	<div class="form">
		<h1>List of Pokemon with this move</h1>
		<% @move.pokemons.each do |pokemon| %>
			<h2><%= link_to pokemon.name, pokemon_path(pokemon) %></h2>
		<% end %>
	</div>
</div>