config/routes.rb
Rails.application.routes.draw do
	root 'pokemons#index'
	resources :bonds, only: [:destroy, :create]
	resource :session
	resources :pokemons, :users, :moves
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bond.rb
class Bond < ApplicationRecord
	belongs_to :user
	belongs_to :pokemon
end

app/models/move.rb
class Move < ApplicationRecord
	has_and_belongs_to_many :pokemons
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
	has_and_belongs_to_many :moves
	has_many :bonds, dependent: :destroy
	has_many :users, through: :bonds
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bonds, dependent: :destroy
	has_many :pokemons, through: :bonds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :get_current_user

  def get_current_user
  	if User.exists?(session[:user_id])
  		@current_user = User.find(session[:user_id])
  	else
  		@current_user = nil
  	end
  end
end

app/controllers/bonds_controller.rb
class BondsController < ApplicationController
	def destroy
		@user = @current_user
		@pokemon = Pokemon.find(params[:id])
		@user.bonds.find_by(pokemon_id: @pokemon).destroy
		redirect_to @user, alert: "Pokemon was released into the wild"
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
	before_action :set_move, only: [:show, :destroy, :update, :edit]
	def index
		@moves = Move.all
	end
	def new
		@move = Move.new
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def create
		@move = Move.create(move_params)
		error "create"
	end
	def edit
		@types = ["Normal", "Fire", "Water", "Electric", "Grass", "Ice", "Fighting", "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost", "Dragon", "Dark", "Steel", "Fairy"]
	end
	def update
		@move.update(move_params)
		error "update"
	end
	def destroy
		@move.destroy
		redirect_to "/moves", alert: "Move was successfully deleted."
	end
	def show

	end

	private

	def set_move
		@move = Move.find(params[:id])
	end
	
	def move_params
		params.require(:move).permit(:name, :damage, :dps, :poke_type, :quick_move)
	end

	def error action
		if @move.save
			redirect_to @move, notice: "Move was successfully #{action}d."
		else
			message = "| "
			@move.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_move_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_move_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @move, alert: "#{ message }"
			end
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		input_email = params[:user][:email]
		if User.exists?(email: input_email)
			@user = User.find_by(email: input_email)
			puts "User found!"
			if @user.password == params[:user][:password]
				session[:user_id] = @user.id
				redirect_to user_path(@user.id), notice: "User successfully signed in."
			else
				puts "Incorrect password"
				redirect_to new_session_path, notice: "Wrong password, please try again"
			end
		else
			puts "User does not exist"
			redirect_to new_session_path, notice: "User does not exist"
		end
	end
	def destroy
		reset_session
		redirect_to :root, notice: "User successfully signed out."
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :destroy, :update, :edit]
	def index
		@users = User.all
	end
	def new
		@user = User.new
	end
	def create
		@user = User.create(user_params)
		session[:user_id] = @user.id
		error "create"
	end
	def edit
	end
	def update
		@user.update(user_params)
		error "update"
	end
	def destroy
		@user.destroy
		redirect_to "/users", alert: "User was successfully deleted."
	end
	def show
	end

	private

	def set_user
		@user = User.find(params[:id])
	end

	def user_params
		params.require(:user).permit(:email, :password, :first_name, :last_name)
	end

	def error action
		if @user.save
			redirect_to @user, notice: "User was successfully #{action}d."
		else
			message = "| "
			@user.errors.full_messages.each do |error|
				message << "#{error} | "
			end
			if action == "create"
				redirect_to new_user_path, alert: "#{ message }"
			elsif action == "update"
				redirect_to edit_user_path, alert: "#{ message } | Nothing has been changed"
			else
				redirect_to @user, alert: "#{ message }"
			end
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bonds_helper.rb
module BondsHelper
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/pokemons/edit.html.erb
<div class="form">
	<%= form_for @pokemon do |f| %>
	<%= link_to 'Delete', @pokemon, :class => "remove", 
    	method: :delete,
    	data: { confirm: 'Are you sure you want to delete?' } %>
	  	<div class="form-item">
	  		<%= f.select :name, options_for_select(@pokemons.map{ |i| i }, @pokemon.name) %>
	  	</div>
	  	<br>
	  	<div class="form-item">
			<h4>CP</h4>
			<%= f.text_field :cp %>
	  	</div>
 		<div class="form-item">
			<h4>Description</h4>
			<%= f.text_area :description, rows: 7 %>
 		</div>
	  	<div class="form-item">
			<h4>Pokemon TYPE</h4>
			<div class="type-wrapper">
				<% @types.each do |type| %>
					<label>
					<input type="radio" name="pokemon[poke_type]" value="<%= type %>" <%= @pokemon.poke_type == type ? "checked" : ""  %>></input>
					<span class="type-icon type-<%= type.downcase %>"><%= type %></span>
					</label>
				<% end %>
			</div>
	   	</div>
	  	<div class="form-item container">
		   	<label class="form-item">
		   		<h4>Quick Move</h4>
		  		<%= select_tag "move1", options_for_select(Move.all.map{ |i| i.quick_move ? i.name : nil }.select{ |i| i }, :selected => @pokemon.moves.first.name) %>
		  	</label>
		  	<br>
		  	<label class="form-item">
		  		<h4>Main Move</h4>
		  		<%= select_tag "move2", options_for_select(Move.all.map{ |i| i.quick_move ? nil : i.name }.select{ |i| i }, :selected => @pokemon.moves.last.name) %>
		  	</label>
	   	</div>

	<%= f.submit "Submit", :class => "remove" %>
	<% end %>
</div>

app/views/pokemons/index.html.erb
<%= form_tag pokemons_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Search for a pokémon", :autofocus => true %>
    <%= submit_tag "Search", :name => nil, class: "search" %>
  </p>
<% end %>
<hr>
<div class="menu">
	<% if @current_user %>
		<%= link_to image_tag("add.png", class: "add"), new_pokemon_path %>
    <% end %>
</div>
<div class="container">
	<% @pokemons.each do |pokemon| %>
		<div class="pokemon type-<%= pokemon.poke_type.downcase %>">
			<% if @current_user %>
				<p class="remove"><%= link_to "Edit", edit_pokemon_path(pokemon) %></p>
			<% end %>
			<h1><%= link_to pokemon.name, pokemon_path(pokemon) %></h1>
			<img class="img" src="https://img.pokemondb.net/sprites/black-white/anim/normal/<%= pokemon.name.downcase %>.gif" width="100px" height="100px">
		</div>
	<% end %>
</div>

app/views/pokemons/new.html.erb
<div class="form">
	<%= form_for @pokemon do |f| %>
	  	<div class="form-item">
	  		<%= f.select :name, options_for_select(@pokemons.map{ |i| i }) %>
	 	 </div>
	 	 <br>
	 	 <div class="form-item">
	 	 <h4>CP</h4>
		  <%= f.text_field :cp %>
	  	</div>
	  	<div class="form-item">
	  		<h4>Description</h4>
		  <%= f.text_area :description, rows: 7 %>
	  	</div>
	  	<div class="form-item">
			<h4>Pokemon TYPE:</h4>
			<div class="type-wrapper">
				<% @types.each do |type| %>
					<label>
						<input type="radio" <%= type == "Normal" ? "checked" : ""  %> name="pokemon[poke_type]" value="<%= type %>"></input>
						<span class="type-icon type-<%= type.downcase %>"><%= type %></span>
					</label>
				<% end %>
			</div>
	   	</div>

	   	<div class="form-item container">
		   	<label class="form-item">
		   		<h4>Quick Move</h4>
		  		<%= select_tag "move1", options_for_select(Move.all.map{ |i| i.quick_move ? i.name : nil }.select{ |i| i }) %>
		  	</label>
		  	<br>
		  	<label class="form-item">
		  		<h4>Main Move</h4>
		  		<%= select_tag "move2", options_for_select(Move.all.map{ |i| i.quick_move ? nil : i.name }.select{ |i| i }) %>
		  	</label>
	   	</div>

	  <%= f.submit "Submit", :class => "remove" %>
	<% end %>
</div>

app/views/pokemons/show.html.erb
<div class="container">
	<div class="column left">
		<img class="img" src="https://img.pokemondb.net/sprites/black-white/anim/normal/<%= @pokemon.name.downcase %>.gif" width="100" height="100">
	</div>
	<div class="column">
		<% if @current_user %>
			<p>
			<%= link_to "Edit", edit_pokemon_path(@pokemon) %> | 
			<%= link_to 'Delete', @pokemon,
		    	method: :delete,
		    	data: { confirm: 'Are you sure you want to delete?' } %> | 
		    	<%= link_to @pokemon do %>
  					<% if @current_user.pokemons.exists?(@pokemon) %>
  						Pokemon Owned
		    		<% else %>
		    			Catch Pokemon
		    			<% @current_user.pokemons << @pokemon %>
		    		<% end %>
				<% end %>
			</p>
		<% end %>
		<h1><%= @pokemon.name %></h1>
		<div class="remove type-icon type-<%= @pokemon.poke_type.downcase %>"><%= @pokemon.poke_type %></div>
		<hr>
		<article><%= @pokemon.description %></article>
		<h4>MAX CP: <%= @pokemon.cp %></h4>
		<h4>Best Moveset</h4>
		<% @pokemon.moves.each do |move| %>
			<span><div class="type-icon type-<%= move.poke_type.downcase %>"><%= move.poke_type %></div> <%= move.name %></span> </br>
		<% end %>
	</div>
</div>
<div class="container">
	<div class="form">
		<h1>Trainers that owns a <%= @pokemon.name %></h1>
		<% @pokemon.users.each do |user| %>
			<h2><%= link_to user.email, user %></h2>
		<% end %>
	</div>
</div>